require 'actions/play_actions/assassinate'
require 'actions/play_actions/coup'
require 'actions/play_actions/exchange'
require 'actions/play_actions/foreign_aid'
require 'actions/play_actions/income'
require 'actions/play_actions/steal'
require 'actions/play_actions/tax'

require 'actions/play_actions/reactions/block'
require 'actions/play_actions/reactions/challenge'